Add HTTP `object_store` to be able to connect without caching in memory… (#393)
Before: 
```
roapi -t taxi=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet,use_memory_table=false,format=parquet
[2025-04-23T22:43:25Z INFO  roapi::context] loading `uri(https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet)` as table `taxi`
error: Failed to build context: Failed to load table: Table error: Failed to infer table schema: Internal error: No suitable object store found for https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet. See `RuntimeEnv::register_object_store`.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

After:
```
roapi -t 'taxi=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet,use_memory_table=false,format=parquet'`
[2025-04-23T22:47:00Z INFO  roapi::context] loading `uri(https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet)` as table `taxi`
[2025-04-23T22:47:00Z INFO  roapi::context] registered `uri(https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet)` as table `taxi`
[2025-04-23T22:47:00Z INFO  roapi::startup] Running in read-only mode.
[2025-04-23T22:47:00Z INFO  roapi::startup] 🚀 Listening on 127.0.0.1:5432 for Postgres traffic...
[2025-04-23T22:47:00Z INFO  roapi::startup] 🚀 Listening on 127.0.0.1:32010 for FlightSQL traffic...
[2025-04-23T22:47:00Z INFO  roapi::startup] 🚀 Listening on 127.0.0.1:8080 for HTTP traffic...
```