fix: add missing explicit lifetime in `ExcelSubrange` return type for rust 1.83 build (#353)
seeing some regression build failure when building roapi 0.12.0 against
rust 1.83.0

```
  error: elided lifetime has a name
    --> columnq/src/table/excel.rs:48:10
     |
  41 | impl<'a> ExcelSubrange<'a> {
     |      -- lifetime `'a` declared here
  ...
  48 |     ) -> ExcelSubrange {
     |          ^^^^^^^^^^^^^ this elided lifetime gets resolved as `'a`
     |
  note: the lint level is defined here
    --> columnq/src/lib.rs:1:9
     |
  1  | #![deny(warnings)]
     |         ^^^^^^^^
     = note: `#[deny(elided_named_lifetimes)]` implied by `#[deny(warnings)]`
```

relates to https://github.com/Homebrew/homebrew-core/pull/199379

Signed-off-by: Rui Chen <rui@chenrui.dev>